In [1]:
import pandas as pd

In [2]:
# Import the dataset, which had piblication rate and landslide features merged by Wenting
bik = pd.read_csv('bik_pub_landslide.csv', index_col=[0])
bik = pd.DataFrame(bik)
bik

,First Author,Authors,Title,Citation,DOI,Year,Month,0,1,2,...,Degree area,Lab Size,Highest Degree,Other Jornals Published in,Publications,Career Years,Publication Rate,event_cnt,fatality_cnt,injury_cnt
0,Adis Tasanarong,"Adis Tasanarong, Supranee Kongkham, and Sookka...",Dual Inhibiting Senescence and Epithelial-to-M...,"2 BioMed Research International - Volume 2013,...",10.1155/2013/308130,2013,NaN,NaN,NaN,1.0,...,Medicine,NaN,PhD,"Europe PubMed Central, Hindawi Limited, PubMed...",30.0,20.0,1.50,77.0,75.0,10.0
1,Akrem Abdulsid,"Akrem Abdulsid, Alexander Fletcher, Fiona Lyall",Heat Shock Protein 27 Is Spatially Distributed...,"PLOS ONE, August 2013 | Volume 8 | Issue 8 | e...",10.1371/journal.pone.0071127,2013,08August,NaN,NaN,NaN,...,Medicine,NaN,PhD,"Europe PubMed Central, PubMed Central, Public ...",7.0,5.0,1.40,229.0,4.0,5.0
2,Alexandr V. Bazhin,"Alexandr V. Bazhin, Olga N. Shifrina, Marina S...",Low titre autoantibodies against recoverin in ...,Lung Cancer 34 (2001) 99�104,10.1016/S0169-5002(01)00212-4,2001,NaN,NaN,NaN,1.0,...,Enzymology,NaN,NaN,Elsevier Science,116.0,19.0,6.11,13.0,7.0,0.0
3,Ambrish Kumar,"Ambrish Kumar, Daping Fan, Donald J. DiPette, ...","Sparstolonin B, a Novel Plant Derived Compound...","PLOS ONE, May 2014 | Volume 9 | Issue 5 | e96343",10.1371/journal.pone.0096343,2014,05May,NaN,1.0,NaN,...,Pathology,NaN,PhD,"Europe PubMed Central, PubMed Central, Public ...",45.0,17.0,2.65,2992.0,96.0,50.0
4,Ana Mena,"Ana Mena, Virginia Plasencia, Laura Garci_a, O...",Characterization of a Large Outbreak by CTX-M-...,"J. Clin. Microbiol. 2006, 44(8):2831",10.1128/JCM.00418-06,2006,JCM,NaN,NaN,NaN,...,Microbiología,NaN,NaN,"Atypon, Europe PubMed Central, PubMed Central",27.0,19.0,1.42,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,Zhenni Zhang,"Zhenni Zhang, Jianrui Lv, Xiaoming Lei, Siyuan...",Baicalein Reduces the Invasion of Glioma Cells...,"PLOS One, February 2014 | Volume 9 | Issue 2 |...",10.1371/journal.pone.0090318,2014,02February,NaN,NaN,1.0,...,Anesthesia,NaN,NaN,"Europe PubMed Central, PubMed Central, Public ...",33.0,18.0,1.83,426.0,4945.0,318.0
210,Zhiqiang Wang,"Zhiqiang Wang, Baofang Jin, Xindong Zhang, Yug...",Yangjing Capsule Extract Promotes Proliferatio...,"Evidence-Based Complementary, and Alternative ...",10.1155/2014/640857,2014,NaN,NaN,NaN,NaN,...,Medicine,NaN,PhD,"Europe PubMed Central, Hindawi Limited, PubMed...",1623.0,24.0,67.62,426.0,4945.0,318.0
211,Zhongpu Chen,"Zhongpu Chen, Xiaodong Pan, Yuyu Yao, Fengdi Y...",Epigenetic Regulation of Cardiac Progenitor Ce...,"PLOS ONE, July 2013 | Volume 8 | Issue 7 | e69...",10.1371/journal.pone.0069134,2013,07July,NaN,NaN,1.0,...,Cardiology,NaN,NaN,"Europe PubMed Central, PubMed Central, Public ...",20.0,8.0,2.50,426.0,4945.0,318.0
212,Zhongyuan Wang,"Zhongyuan Wang, Yanping Wu, Haifeng Wang, Yang...",Interplay of mevalonate and Hippo pathways reg...,"PNAS | Published online December 23, 2013 | E8...",10.1073/pnas.1319190110,2014,NaN,NaN,NaN,1.0,...,Computer Science,NaN,PhD,"Europe PubMed Central, HighWire, PubMed Central",132.0,20.0,6.60,426.0,4945.0,318.0
213,NaN,"Z Zhang, X Liu, B Feng, N Liu, Q Wu, Y Han, Y ...","STIM1, a direct target of microRNA-185, promot...","Oncogene (2014), 1�13",10.1038/onc.2014.404,2014,NaN,NaN,NaN,1.0,...,Cancer Biology,NaN,NaN,"Europe PubMed Central, Nature Publishing Group...",NaN,NaN,NaN,426.0,4945.0,318.0

In [3]:
# Clean the university column for matching
bik['University'] = bik['University'].str.replace(' School of Medicine', '')
bik['University'] = bik['University'].str.replace(' Medical School', '')
bik['University'] = bik['University'].str.replace('Medical School of ', '')
bik['University'] = bik['University'].str.replace(' School of Dentistry', '')
bik['University'] = bik['University'].str.replace('Jiaotong', 'Jiao Tong')

bik['University'] = bik['University'].replace('Harvard', 'Harvard University')
bik['University'] = bik['University'].replace('Yale', 'Yale University')
bik['University'] = bik['University'].replace('Washington University', 'Washington University in St Louis')
bik['University'] = bik['University'].replace('The University of Hong Kong', 'University of Hong Kong')
bik['University'] = bik['University'].replace('The Ohio State University', 'Ohio State University')
bik['University'] = bik['University'].replace('The Johns Hopkins University', 'Johns Hopkins University')
bik['University'] = bik['University'].replace('Johns Hopkins University School', 'Johns Hopkins University')
bik['University'] = bik['University'].replace('University of Vermont College of Medicine', 'University of Vermont')
bik['University'] = bik['University'].replace('Korea University College of Medicine', 'Korea University')

In [4]:
# Import the world university ranking dataset
data = pd.read_csv('RawRanking.csv')
data = pd.DataFrame(data)
data = data[data['year'] == 2013].reset_index(drop=True)

,world_rank,university_name,country,teaching,international,research,citations,income,total_score,num_students,student_staff_ratio,international_students,female_male_ratio,year
0,1,California Institute of Technology,United States of America,96.3,59.8,99.4,99.7,95.6,95.5,"2,243",6.9,27%,33 : 67,2013
1,2,Stanford University,United States of America,95.0,56.6,98.8,99.3,62.4,93.7,"15,596",7.8,22%,42 : 58,2013
2,2,University of Oxford,United Kingdom,89.7,88.7,98.1,95.6,79.8,93.7,"19,919",11.6,34%,46 : 54,2013
3,4,Harvard University,United States of America,94.9,63.7,98.6,99.2,39.9,93.6,"20,152",8.9,25%,NaN,2013
4,5,Massachusetts Institute of Technology,United States of America,92.9,81.6,89.2,99.9,92.9,93.1,"11,074",9.0,33%,37 : 63,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,351-400,University of Valencia,Spain,17.2,40.8,14.5,62.8,32.5,-,"58,413",15.4,9%,60 : 40,2013
396,351-400,University of Vigo,Spain,19.4,26.9,9.5,63.7,36.6,-,"22,793",19.0,3%,51 : 49,2013
397,351-400,University of Warsaw,Poland,23.2,39.8,18.4,54.0,27.9,-,"49,292",14.1,7%,67 : 33,2013
398,351-400,University of Wyoming,United States of America,18.6,28.1,24.2,47.5,30.9,-,NaN,NaN,NaN,NaN,2013
399,351-400,Waseda University,Japan,28.9,32.8,21.3,37.8,30.8,-,"52,316",16.9,8%,35 : 65,2013

In [5]:
# Extract selected features to a new dataframe
ranking = pd.DataFrame()
ranking['University'] = data['university_name']
ranking['World Rank'] = data['world_rank']
ranking['Teaching'] = data['teaching']
ranking['Research'] = data['research']

                                University World Rank  Teaching  Research
0       California Institute of Technology          1      96.3      99.4
1                      Stanford University          2      95.0      98.8
2                     University of Oxford          2      89.7      98.1
3                       Harvard University          4      94.9      98.6
4    Massachusetts Institute of Technology          5      92.9      89.2
..                                     ...        ...       ...       ...
395                 University of Valencia    351-400      17.2      14.5
396                     University of Vigo    351-400      19.4       9.5
397                   University of Warsaw    351-400      23.2      18.4
398                  University of Wyoming    351-400      18.6      24.2
399                      Waseda University    351-400      28.9      21.3

[400 rows x 4 columns]

In [6]:
# Merge the two datasets on University
merge = pd.merge(bik, ranking, on='University', how='left')

,First Author,Authors,Title,Citation,DOI,Year,Month,0,1,2,...,Other Jornals Published in,Publications,Career Years,Publication Rate,event_cnt,fatality_cnt,injury_cnt,World Rank,Teaching,Research
0,Adis Tasanarong,"Adis Tasanarong, Supranee Kongkham, and Sookka...",Dual Inhibiting Senescence and Epithelial-to-M...,"2 BioMed Research International - Volume 2013,...",10.1155/2013/308130,2013,NaN,NaN,NaN,1.0,...,"Europe PubMed Central, Hindawi Limited, PubMed...",30.0,20.0,1.50,77.0,75.0,10.0,NaN,NaN,NaN
1,Akrem Abdulsid,"Akrem Abdulsid, Alexander Fletcher, Fiona Lyall",Heat Shock Protein 27 Is Spatially Distributed...,"PLOS ONE, August 2013 | Volume 8 | Issue 8 | e...",10.1371/journal.pone.0071127,2013,08August,NaN,NaN,NaN,...,"Europe PubMed Central, PubMed Central, Public ...",7.0,5.0,1.40,229.0,4.0,5.0,NaN,NaN,NaN
2,Alexandr V. Bazhin,"Alexandr V. Bazhin, Olga N. Shifrina, Marina S...",Low titre autoantibodies against recoverin in ...,Lung Cancer 34 (2001) 99�104,10.1016/S0169-5002(01)00212-4,2001,NaN,NaN,NaN,1.0,...,Elsevier Science,116.0,19.0,6.11,13.0,7.0,0.0,NaN,NaN,NaN
3,Ambrish Kumar,"Ambrish Kumar, Daping Fan, Donald J. DiPette, ...","Sparstolonin B, a Novel Plant Derived Compound...","PLOS ONE, May 2014 | Volume 9 | Issue 5 | e96343",10.1371/journal.pone.0096343,2014,05May,NaN,1.0,NaN,...,"Europe PubMed Central, PubMed Central, Public ...",45.0,17.0,2.65,2992.0,96.0,50.0,276-300,37.5,28.0
4,Ana Mena,"Ana Mena, Virginia Plasencia, Laura Garci_a, O...",Characterization of a Large Outbreak by CTX-M-...,"J. Clin. Microbiol. 2006, 44(8):2831",10.1128/JCM.00418-06,2006,JCM,NaN,NaN,NaN,...,"Atypon, Europe PubMed Central, PubMed Central",27.0,19.0,1.42,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,Zhenni Zhang,"Zhenni Zhang, Jianrui Lv, Xiaoming Lei, Siyuan...",Baicalein Reduces the Invasion of Glioma Cells...,"PLOS One, February 2014 | Volume 9 | Issue 2 |...",10.1371/journal.pone.0090318,2014,02February,NaN,NaN,1.0,...,"Europe PubMed Central, PubMed Central, Public ...",33.0,18.0,1.83,426.0,4945.0,318.0,NaN,NaN,NaN
210,Zhiqiang Wang,"Zhiqiang Wang, Baofang Jin, Xindong Zhang, Yug...",Yangjing Capsule Extract Promotes Proliferatio...,"Evidence-Based Complementary, and Alternative ...",10.1155/2014/640857,2014,NaN,NaN,NaN,NaN,...,"Europe PubMed Central, Hindawi Limited, PubMed...",1623.0,24.0,67.62,426.0,4945.0,318.0,NaN,NaN,NaN
211,Zhongpu Chen,"Zhongpu Chen, Xiaodong Pan, Yuyu Yao, Fengdi Y...",Epigenetic Regulation of Cardiac Progenitor Ce...,"PLOS ONE, July 2013 | Volume 8 | Issue 7 | e69...",10.1371/journal.pone.0069134,2013,07July,NaN,NaN,1.0,...,"Europe PubMed Central, PubMed Central, Public ...",20.0,8.0,2.50,426.0,4945.0,318.0,NaN,NaN,NaN
212,Zhongyuan Wang,"Zhongyuan Wang, Yanping Wu, Haifeng Wang, Yang...",Interplay of mevalonate and Hippo pathways reg...,"PNAS | Published online December 23, 2013 | E8...",10.1073/pnas.1319190110,2014,NaN,NaN,NaN,1.0,...,"Europe PubMed Central, HighWire, PubMed Central",132.0,20.0,6.60,426.0,4945.0,318.0,52,74.5,76.4
213,NaN,"Z Zhang, X Liu, B Feng, N Liu, Q Wu, Y Han, Y ...","STIM1, a direct target of microRNA-185, promot...","Oncogene (2014), 1�13",10.1038/onc.2014.404,2014,NaN,NaN,NaN,1.0,...,"Europe PubMed Central, Nature Publishing Group...",NaN,NaN,NaN,426.0,4945.0,318.0,NaN,NaN,NaN

In [7]:
# Export the merged dataset and pass it to Ziquan for merging the lab size
compression_opts = dict(method='zip', archive_name='bik_pub_landslide_ranking.csv')  
merge.to_csv('bik_pub_landslide_ranking.zip', index=False, compression = compression_opts)